### ISSUE TITLE
sudoers file

### ISSUE THREAD

**Issue by obperryo-wex** [davoclock/devops-setup#1]
This command `echo "${USERNAME}    ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers >> /dev/null` does not update the sudoers file for me, however, it it does if I remvoe the  ` >> /dev/null ` from the end.

Also, after I finish all your instructions, how do I get Amazon2 Linux to launch with my user as default?

**Comment by davoclock** [comment]
I've removed >> /dev/null, thanks for pointing that out.

As far as the default user, you could start the WSL instance with:

> wsl -u user Amazon2

I've added that option to the README guide. Thanks!
